title:            Z·X·M
description:      Product Designer ？ Yes.
url:              zxming.com # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Zxming # Your name.
disqus_shortname: zxming # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         About
    url:          /about
  - name:         UICN
    url:          http://i.ui.cn/ucenter/34804
    external:     true
  - name:         Weibo
    url:          http://weibo.com/zxmingcn
    external:     true
  - name:         Email
    url:          mailto:i@zxming.com
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
